version: "3.8"
services:
  gui-app:
    image: dorowu/ubuntu-desktop-lxde-vnc:focal
    container_name: dentex-gui
    ports:
      - "6080:80"  # VNC web interface
      - "5900:5900"  # VNC port
    environment:
      - VNC_PASSWORD=dentex123
      - RESOLUTION=1920x1080
    volumes:
      - .:/app
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    command: >
      bash -c "
        apt-get update && apt-get install -y python3-pip python3-venv git curl wget &&
        pip3 install jupyterlab ipykernel &&
        mkdir -p /app/notebooks &&
        cd /app &&
        jupyter lab --notebook-dir=/app/notebooks --ip=0.0.0.0 --allow-root --port=8888 --no-browser &
        /startup.sh
      "
    restart: unless-stopped
